spring.application.name=compte
server.servlet.context-path=/api
server.port=8081

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/banque?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# ========================================
# Configuration RabbitMQ
# ========================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Nom de la queue
rabbitmq.queue.transaction=transaction.queue
rabbitmq.exchange.transaction=transaction.exchange
rabbitmq.routing.key.transaction=transaction.routing.key

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
# Scanner uniquement le package controller (évite le conflit avec le Feign client)
springdoc.packages-to-scan=sn.ec2lt.banque.controller